### ISSUE TITLE
style not loaded

### ISSUE THREAD

**Issue by abbasudo** [alireza-h/laravel-devtools#2]
I installed the package and followed the installation guide . but when i navigated to the route it didnt load the css files 
how can i fix this

![image](https://user-images.githubusercontent.com/86796762/151863892-3dfde33a-4491-44e1-b520-bed50ab40f1b.png)

**Comment by alireza-h** [comment]
Run this command to publish assets, and check `public/vendeor/devtools` directory
```
php artisan vendor:publish --tag="devtools.assets"
```
